---
- hosts: localhost
  become: yes
  vars:
    cli_user: ""
    cli_username: "Test Build"
    g_password: global@123
    user: ""

  tasks:
    - name: Testing rest api
      debug: msg="{{cli_username}}"
