---
- block:
    - name: Build mismatch Reverting the deployment
      unarchive:
        src: "{{ last_backup }}"
        dest: "/var/www/html"
        remote_src: yes
    
    - name: start service
      service:
        name: apache2
        state: started
      register: apache_start
      
    - debug: msg=" apache restarted"
      when: apache_start.state == 'started'
      
  when: build_num != build_ver
